<a href="https://colab.research.google.com/github/Tiberu2611/Bai-Tap-if-else/blob/master/Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Câu 1: Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá
trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình):
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

In [10]:
a = np.arange(5, 6, 2, dtype=int)
a1 = np.transpose(a)
b = np.linspace(5,11, 7)
b1 = np.transpose(b)
c = np.logspace(1.0, 7.0, num=7, base = 2)
c1 = np.transpose(c)
d = np.random.rand(1,7)
d1 = np.transpose(d)
print(a)
print(a.ndim, a1.ndim, a.shape, a1.shape)
print(b)
print(b.ndim, b1.ndim, b.shape, b1.shape)
print(c)
print(C.ndim, c1.ndim, c.shape, c1.shape)
print(d)
print(d.ndim, d1.ndim, d.shape, d1.shape)

[5]
1 1 (1,) (1,)
[ 5.  6.  7.  8.  9. 10. 11.]
1 1 (7,) (7,)
[  2.   4.   8.  16.  32.  64. 128.]
1 1 (7,) (7,)
[[0.50048262 0.17819005 0.61518994 0.28593286 0.57711881 0.97181638
  0.09327609]]
2 2 (1, 7) (7, 1)


Câu 2: Sử dụng thư viện Numpy, hãy tạo ra ma trận a10x7 với giá trị các phần tử của ma trận a
được sinh bởi:
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

Sau mỗi lần ma trận được tạo ra, hãy xuất kết quả ra màn hình và cho biết:
- Số chiều và kích thước của ma trận a và ma trận aT

In [6]:
A = np.arange(0, 70, 1)
A.shape = (10,7)
A1 = np.transpose(A)
B = np.linspace(0, 69, 70)
B.shape = (10,7)
B1 = np.transpose(B)
C = np.logspace(0, 10, num=70, base = 2)
C.shape = (10,7)
C1 = np.transpose(C)
D = np.random.rand(1, 70)
D.shape = (10,7)
D1 = np.transpose(D)
print(A)
print(A.ndim, A1.ndim, A.shape, A1.shape)
print(B)
print(B.ndim, B1.ndim, B.shape, B1.shape)
print(C)
print(C.ndim, C1.ndim, C.shape, C1.shape)
print(D)
print(D.ndim, D1.ndim, D.shape, D1.shape)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
2 2 (10, 7) (7, 10)
[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12. 13.]
 [14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27.]
 [28. 29. 30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39. 40. 41.]
 [42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55.]
 [56. 57. 58. 59. 60. 61. 62.]
 [63. 64. 65. 66. 67. 68. 69.]]
2 2 (10, 7) (7, 10)
[[1.00000000e+00 1.10567512e+00 1.22251746e+00 1.35170714e+00
  1.49454895e+00 1.65248558e+00 1.82711218e+00]
 [2.02019248e+00 2.23367655e+00 2.46972058e+00 2.73070859e+00
  3.01927653e+00 3.33833893e+00 3.69111829e+00]
 [4.08117764e+00 4.51245656e+00 4.98931093e+00 5.51655694e+00
  6.09951974e+00 6.74408719e+00 7.45676939e+00]
 [8.24476436e+00 9.11603079e+00 1.00793684e+01 1.11445068e+01
  1.23222039e+01

Câu 3: Sử dụng thư viện Numpy, hãy:
- Chuyển ma trận a ở câu 2 thành vector. (Gợi ý: sử dụng hàm flatten())
- Chuyển vector vừa được tạo ra ở câu trên thành ma trận. (Gợi ý: sử dụng hàm reshape())

In [11]:
A = np.arange(0, 70, 1)
A.shape = (10,7)
A1 = A.flatten()
A2 = A1.reshape(10,7)
B = np.linspace(0, 69, 70)
B.shape = (10,7)
B1 = B.flatten()
B2 = B1.reshape(10,7)
C = np.logspace(0, 10, num=70, base = 2)
C.shape = (10,7)
C1 = C.flatten()
C2 = C1.reshape(10,7)
D = np.random.rand(1, 70)
D.shape = (10,7)
D1 = D.flatten()
D2 = D1.reshape(10,7)
print(A)
print(A1)
print(A2)
print(B)
print(B1)
print(B2)
print(C)
print(C1)
print(C2)
print(D)
print(D1)
print(D2)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12. 13.]
 [14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27.]
 [28. 29. 30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39. 40. 41.]
 [42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55.]
 [56. 57. 58. 59. 60. 61. 62.]
 [63. 64. 65. 66. 67. 68.

Câu 4: Sử dụng thư viện Numpy, hãy:
- Tạo ra 1 ma trận A10x15 với các giá trị được sinh ra bởi hàm logspace();
- Hãy trích rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng);
- Hãy trích rút ra cột thứ 5 của ma trận A (tương ứng với 1 vector cột).

In [13]:
A = np.logspace(0, 149, num=150)
A.shape = (10,15)
A3 = A[3,:]
A5 = A[:,5]
print(A)
print(A3)
print(A5)

[[1.e+000 1.e+001 1.e+002 1.e+003 1.e+004 1.e+005 1.e+006 1.e+007 1.e+008
  1.e+009 1.e+010 1.e+011 1.e+012 1.e+013 1.e+014]
 [1.e+015 1.e+016 1.e+017 1.e+018 1.e+019 1.e+020 1.e+021 1.e+022 1.e+023
  1.e+024 1.e+025 1.e+026 1.e+027 1.e+028 1.e+029]
 [1.e+030 1.e+031 1.e+032 1.e+033 1.e+034 1.e+035 1.e+036 1.e+037 1.e+038
  1.e+039 1.e+040 1.e+041 1.e+042 1.e+043 1.e+044]
 [1.e+045 1.e+046 1.e+047 1.e+048 1.e+049 1.e+050 1.e+051 1.e+052 1.e+053
  1.e+054 1.e+055 1.e+056 1.e+057 1.e+058 1.e+059]
 [1.e+060 1.e+061 1.e+062 1.e+063 1.e+064 1.e+065 1.e+066 1.e+067 1.e+068
  1.e+069 1.e+070 1.e+071 1.e+072 1.e+073 1.e+074]
 [1.e+075 1.e+076 1.e+077 1.e+078 1.e+079 1.e+080 1.e+081 1.e+082 1.e+083
  1.e+084 1.e+085 1.e+086 1.e+087 1.e+088 1.e+089]
 [1.e+090 1.e+091 1.e+092 1.e+093 1.e+094 1.e+095 1.e+096 1.e+097 1.e+098
  1.e+099 1.e+100 1.e+101 1.e+102 1.e+103 1.e+104]
 [1.e+105 1.e+106 1.e+107 1.e+108 1.e+109 1.e+110 1.e+111 1.e+112 1.e+113
  1.e+114 1.e+115 1.e+116 1.e+117 1.e+118 1.e+119]


Câu 5: Thực hiện các yêu cầu sau:
- Xây dựng hàm tính giá trị trung bình
- Xây dựng hàm tính giá trị trung vị
- Xây dựng hàm tính giá trị yếu vị
- Xây dựng hàm tính phương sai
- Xây dựng hàm tính độ lệch chuẩn
- Hãy tạo ra ma trận A15x10 với các giá trị sinh bởi hàm arrange()
- Áp dụng 5 hàm ở trên cho từng hàng của ma trận A
- Áp dụng 5 hàm ở trên cho từng cột của ma trận A

In [14]:
def tinh_tb(a): 
    s = 0
    for i in range(0,len(a)): 
        s += a[i]
    tb = s/len(a)
    return tb
a = np.random.randint(0, 50, size = (15,10))
b = np.apply_along_axis(tinh_tb, 0, a)
c = np.apply_along_axis(tinh_tb, 1, a)
print(a)
print("áp dụng trên cột", b)
print("áp dụng trên hàng", c)

[[11 39 10 44 23  8 36 46 17 12]
 [35 45 43 45 37 33 37 11 11 29]
 [10 34 12  2  9 25 17 18 41 29]
 [25 43 14 36 10 41 27  8  6 42]
 [49 33  4 46 36  4 32  2 47 10]
 [48 48  6 11 33  4 32  3 30 22]
 [37  0 14 14 14 12 36  6  4 35]
 [10 48 12 24 23 43 29 33  9 47]
 [32 29 14 48 34 46 40 47  9 43]
 [30 14  5 40  9 28 15 30 25 34]
 [27 22 15 12  1 15 43 43  6  7]
 [17 25 35 12 49 22 33 33 25 28]
 [ 5 41 41 19 32 21 14  5 29  3]
 [15 16 40  2 18 48 27  1 42 14]
 [17 12 17 10 37 25 39 21 46 48]]
áp dụng trên cột [24.53333333 29.93333333 18.8        24.33333333 24.33333333 25.
 30.46666667 20.46666667 23.13333333 26.86666667]
áp dụng trên hàng [24.6 32.6 19.7 25.2 26.3 23.7 17.2 27.8 34.2 23.  19.1 27.9 21.  22.3
 27.2]
