<a href="https://colab.research.google.com/github/Tiberu2611/Bai-Tap-if-else/blob/master/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1:Xét không gian R3, một điểm A trong không gian này có tọa độ là (5, 7, 14). Hãy khởi tạo giá trị của điểm A nêu trên bằng Numpy.

In [ ]:
import numpy as np
A = np.array([5, 7, 14])
print(A)

[ 5  7 14]


Bài 2: Mở rộng không gian lên R15, điểm A trong không gian này có tọa độ là (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15). Hãy khởi tạo điểm A trong không gian 15 chiều này bằng Numpy.

In [2]:
import numpy as np
A = np.arange(1,16,1)
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Bài 3: Hãy viết chương trình sinh ngẫu nhiên một vector trong không gian Rn với n là số nguyên dương được nhập vào từ bàn phím. Yêu cầu: sử dụng Numpy.

In [7]:
import numpy as np
n = int(input("Nhập n: "))
matr = np.random.randint(1,10,size = (n))
print(matr)

Nhập n: 5
[2 1 8 1 4]


Bài 4: Hãy viết chương trình tính chiều dài của vector OA , biết công thức tổng quát để tính chiều dài vector OA trong không gian Rn là:


In [22]:
import numpy as np
import math
OA = np.random.randint(1,10,size = 3)
print(OA)
tong = 0
for i in OA:
  tong = tong+i**2
print("chiều dài vecto OA: ", math.sqrt(tong))

[7 7 9]
chiều dài vecto OA:  13.379088160259652


Bài 5 Trong không gian Rn , hãy sinh ngẫu nhiên 2 điểm A và B. Xác định vector AB⃗⃗⃗⃗⃗ và tính chiều dài của vector này ‖AB⃗⃗⃗⃗⃗ ‖. Lưu ý: sử dụng Numpy.

In [21]:
import numpy as np
A = np.random.randint(1,10,size = 3)
print("Vecto A: ", A)
B = np.random.randint(1,10,size = 3)
print("Vecto B: ", B)
AB = B - A
print("Vecto AB: ", AB)

Vecto A:  [3 4 2]
Vecto B:  [9 7 4]
Vecto AB:  [6 3 2]


Bài 6: Tích vô hướng của 2 vector a & b⃗ (dot product hoặc inner product hoặc scalar product) được tính theo công thức tổng quát là:

In [33]:
import numpy as np
a = np.random.randint(1,10, size = (3,3))
b = np.random.randint(1,10, size = (3,3))
print(a)
print(b)
print("tích vô hướng của 2 vecto a&b: \n", np.inner(a, b))

[[8 8 1]
 [6 7 2]
 [5 7 5]]
[[6 5 2]
 [4 1 1]
 [2 9 7]]
tích vô hướng của 2 vecto a&b: 
 [[ 90  41  95]
 [ 75  33  89]
 [ 75  32 108]]


Bài 7

In [34]:
import numpy as np
a = np.random.randint(1,10, size = (3,3))
b = np.random.randint(1,10, size = (3,3))
print(a)
print(b)
print("tích hữu hướng của 2 vecto a&b: \n", np.cross(a, b))

[[2 7 9]
 [7 8 8]
 [9 8 2]]
[[6 7 6]
 [6 1 2]
 [4 5 6]]
tích hữu hướng của 2 vecto a&b: 
 [[-21  42 -28]
 [  8  34 -41]
 [ 38 -46  13]]


Bài 8

In [36]:
import numpy as np
a = np.random.randint(1,10, size = (3,3))
print(a)
a_ = np.transpose(a)
print("ma trận chuyển bị của a là : \n", a_)

[[4 3 7]
 [9 1 8]
 [8 6 3]]
ma trận chuyển bị của a là : 
 [[4 9 8]
 [3 1 6]
 [7 8 3]]


Bài 9

In [39]:
import numpy as np
a = [1, 2, 3, 4, 5]
b = [[1], [2], [3], [4], [5]]
print(a)
print(b)
a_ = np.array(a)
print(a_)
b_ = np.array(b)
print(b_)
a_t = np.transpose(a_)
print(a_t)
b_t = np.transpose(b_)
print(b_t)


[1, 2, 3, 4, 5]
[[1], [2], [3], [4], [5]]
[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3 4 5]
[[1 2 3 4 5]]


Bài 10

In [40]:
import numpy as np
n = int(input("Nhập chiều không gian n: "))
a = np.random.randint(1,10, size = n)
print(a)
b = np.random.randint(1,10, size = n)
print(b)
m = int(input("Nhập m: "))
print("phép nhân ma là: ", m*a)
print("phép cộng 2 vecto a&b: ", a + b)

Nhập chiều không gian n: 4
[3 1 7 9]
[4 1 6 4]
Nhập m: 2
phép nhân ma là:  [ 6  2 14 18]
phép cộng 2 vecto a&b:  [ 7  2 13 13]
